package com.tingyu.domain.userinfo;

import java.util.Date;

public class TAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.c_id
     *
     * @mbggenerated
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.c_username
     *
     * @mbggenerated
     */
    private String cUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.c_password
     *
     * @mbggenerated
     */
    private String cPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.c_invite_code
     *
     * @mbggenerated
     */
    private String cInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.dt_invite_time
     *
     * @mbggenerated
     */
    private Date dtInviteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.dt_last_modify_time
     *
     * @mbggenerated
     */
    private Date dtLastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.t_admin.n_valid
     *
     * @mbggenerated
     */
    private Integer nValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @mbggenerated
     */
    public TAdmin(String cId, String cUsername, String cPassword, String cName, String cInviteCode, Date dtInviteTime, Date dtLastModifyTime, Integer nValid) {
        this.cId = cId;
        this.cUsername = cUsername;
        this.cPassword = cPassword;
        this.cName = cName;
        this.cInviteCode = cInviteCode;
        this.dtInviteTime = dtInviteTime;
        this.dtLastModifyTime = dtLastModifyTime;
        this.nValid = nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @mbggenerated
     */
    public TAdmin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.c_id
     *
     * @return the value of userinfo.t_admin.c_id
     *
     * @mbggenerated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.c_id
     *
     * @param cId the value for userinfo.t_admin.c_id
     *
     * @mbggenerated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.c_username
     *
     * @return the value of userinfo.t_admin.c_username
     *
     * @mbggenerated
     */
    public String getcUsername() {
        return cUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.c_username
     *
     * @param cUsername the value for userinfo.t_admin.c_username
     *
     * @mbggenerated
     */
    public void setcUsername(String cUsername) {
        this.cUsername = cUsername == null ? null : cUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.c_password
     *
     * @return the value of userinfo.t_admin.c_password
     *
     * @mbggenerated
     */
    public String getcPassword() {
        return cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.c_password
     *
     * @param cPassword the value for userinfo.t_admin.c_password
     *
     * @mbggenerated
     */
    public void setcPassword(String cPassword) {
        this.cPassword = cPassword == null ? null : cPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.c_name
     *
     * @return the value of userinfo.t_admin.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.c_name
     *
     * @param cName the value for userinfo.t_admin.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.c_invite_code
     *
     * @return the value of userinfo.t_admin.c_invite_code
     *
     * @mbggenerated
     */
    public String getcInviteCode() {
        return cInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.c_invite_code
     *
     * @param cInviteCode the value for userinfo.t_admin.c_invite_code
     *
     * @mbggenerated
     */
    public void setcInviteCode(String cInviteCode) {
        this.cInviteCode = cInviteCode == null ? null : cInviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.dt_invite_time
     *
     * @return the value of userinfo.t_admin.dt_invite_time
     *
     * @mbggenerated
     */
    public Date getDtInviteTime() {
        return dtInviteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.dt_invite_time
     *
     * @param dtInviteTime the value for userinfo.t_admin.dt_invite_time
     *
     * @mbggenerated
     */
    public void setDtInviteTime(Date dtInviteTime) {
        this.dtInviteTime = dtInviteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.dt_last_modify_time
     *
     * @return the value of userinfo.t_admin.dt_last_modify_time
     *
     * @mbggenerated
     */
    public Date getDtLastModifyTime() {
        return dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.dt_last_modify_time
     *
     * @param dtLastModifyTime the value for userinfo.t_admin.dt_last_modify_time
     *
     * @mbggenerated
     */
    public void setDtLastModifyTime(Date dtLastModifyTime) {
        this.dtLastModifyTime = dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.t_admin.n_valid
     *
     * @return the value of userinfo.t_admin.n_valid
     *
     * @mbggenerated
     */
    public Integer getnValid() {
        return nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.t_admin.n_valid
     *
     * @param nValid the value for userinfo.t_admin.n_valid
     *
     * @mbggenerated
     */
    public void setnValid(Integer nValid) {
        this.nValid = nValid;
    }
}