package com.tingyu.dao.book;

import com.tingyu.domain.book.TBook;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * The interface T book mapper.
 */
public interface TBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param cId the c id
     * @return the int
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insert(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insertSelective(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param cId the c id
     * @return the t book
     * @mbggenerated
     */
    TBook selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKey(TBook record);

    /**
     * Gets all books.
     *
     * @param nPageSize the n page size
     * @param nPageNow  the n page now
     * @return the all books
     */
    List<TBook> getAllBooksByPage(@Param("nPageSize") int nPageSize, @Param("nPageNow") int nPageNow);
}