package com.tingyu.dao.book;

import com.tingyu.domain.book.TChapter;

import java.util.List;

/**
 * The interface T chapter mapper.
 */
public interface TChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param cId the c id
     * @return the int
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insert(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insertSelective(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param cId the c id
     * @return the t chapter
     * @mbggenerated
     */
    TChapter selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKey(TChapter record);

    /**
     * Select by book id list.
     *
     * @param cBookId the c book id
     * @return the list
     */
    List<TChapter> selectByBookId(String cBookId);
}