package com.tingyu.dao.userinfo;

import com.tingyu.domain.userinfo.TAdmin;
import org.apache.ibatis.annotations.Param;

/**
 * The interface T admin mapper.
 */
public interface TAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param cId the c id
     * @return the int
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insert(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insertSelective(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param cId the c id
     * @return the t admin
     * @mbggenerated
     */
    TAdmin selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo.t_admin
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKey(TAdmin record);

    /**
     * Select by username and password tadmin.
     *
     * @param username the username
     * @param password the password
     * @return the tadmin
     */
    TAdmin selectByUsernameAndPassword(@Param("cUsername") String username, @Param("cPassword") String password);
}