package com.tingyu.dao.basic;

import com.tingyu.domain.basic.TCodeInfo;
import com.tingyu.domain.basic.TCodeInfoKey;

import java.util.List;

/**
 * The interface T code info mapper.
 */
public interface TCodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param key the key
     * @return the int
     * @mbggenerated
     */
    int deleteByPrimaryKey(TCodeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insert(TCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insertSelective(TCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param key the key
     * @return the t code info
     * @mbggenerated
     */
    TCodeInfo selectByPrimaryKey(TCodeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKey(TCodeInfo record);

    /**
     * Select all code info list.
     *
     * @return the list
     */
    List<TCodeInfo> selectAllCodeInfo();
}