package com.tingyu.dao.basic;

import com.tingyu.bean.cache.CodeBean;
import com.tingyu.domain.basic.TCodeType;

import java.util.List;

/**
 * The interface T code type mapper.
 */
public interface TCodeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param nCodeType the n code type
     * @return the int
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer nCodeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insert(TCodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int insertSelective(TCodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param nCodeType the n code type
     * @return the t code type
     * @mbggenerated
     */
    TCodeType selectByPrimaryKey(Integer nCodeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_type
     *
     * @param record the record
     * @return the int
     * @mbggenerated
     */
    int updateByPrimaryKey(TCodeType record);

    /**
     * Select all code type list.
     *
     * @return the list
     */
    List<TCodeType> selectAllCodeType();


    /**
     * Select all code type and info list.
     * 查询有效的单值代码信息，按照show_order排序
     * @return the list
     */
    List<CodeBean> selectAllCodeTypeAndInfo();
}