package com.tingyu.domain.basic;

public class TCodeInfo extends TCodeInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_code_name
     *
     * @mbggenerated
     */
    private String nCodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_show_order
     *
     * @mbggenerated
     */
    private Integer nShowOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_spelling_code
     *
     * @mbggenerated
     */
    private String nSpellingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_valid
     *
     * @mbggenerated
     */
    private Integer nValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @mbggenerated
     */
    public TCodeInfo(Integer nCodeType, Integer nCode, String nCodeName, Integer nShowOrder, String nSpellingCode, Integer nValid) {
        super(nCodeType, nCode);
        this.nCodeName = nCodeName;
        this.nShowOrder = nShowOrder;
        this.nSpellingCode = nSpellingCode;
        this.nValid = nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @mbggenerated
     */
    public TCodeInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_code_name
     *
     * @return the value of basic.t_code_info.n_code_name
     *
     * @mbggenerated
     */
    public String getnCodeName() {
        return nCodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_code_name
     *
     * @param nCodeName the value for basic.t_code_info.n_code_name
     *
     * @mbggenerated
     */
    public void setnCodeName(String nCodeName) {
        this.nCodeName = nCodeName == null ? null : nCodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_show_order
     *
     * @return the value of basic.t_code_info.n_show_order
     *
     * @mbggenerated
     */
    public Integer getnShowOrder() {
        return nShowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_show_order
     *
     * @param nShowOrder the value for basic.t_code_info.n_show_order
     *
     * @mbggenerated
     */
    public void setnShowOrder(Integer nShowOrder) {
        this.nShowOrder = nShowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_spelling_code
     *
     * @return the value of basic.t_code_info.n_spelling_code
     *
     * @mbggenerated
     */
    public String getnSpellingCode() {
        return nSpellingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_spelling_code
     *
     * @param nSpellingCode the value for basic.t_code_info.n_spelling_code
     *
     * @mbggenerated
     */
    public void setnSpellingCode(String nSpellingCode) {
        this.nSpellingCode = nSpellingCode == null ? null : nSpellingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_valid
     *
     * @return the value of basic.t_code_info.n_valid
     *
     * @mbggenerated
     */
    public Integer getnValid() {
        return nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_valid
     *
     * @param nValid the value for basic.t_code_info.n_valid
     *
     * @mbggenerated
     */
    public void setnValid(Integer nValid) {
        this.nValid = nValid;
    }
}