package com.tingyu.domain.basic;

public class TCodeInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_code_type
     *
     * @mbggenerated
     */
    private Integer nCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic.t_code_info.n_code
     *
     * @mbggenerated
     */
    private Integer nCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @mbggenerated
     */
    public TCodeInfoKey(Integer nCodeType, Integer nCode) {
        this.nCodeType = nCodeType;
        this.nCode = nCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic.t_code_info
     *
     * @mbggenerated
     */
    public TCodeInfoKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_code_type
     *
     * @return the value of basic.t_code_info.n_code_type
     *
     * @mbggenerated
     */
    public Integer getnCodeType() {
        return nCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_code_type
     *
     * @param nCodeType the value for basic.t_code_info.n_code_type
     *
     * @mbggenerated
     */
    public void setnCodeType(Integer nCodeType) {
        this.nCodeType = nCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic.t_code_info.n_code
     *
     * @return the value of basic.t_code_info.n_code
     *
     * @mbggenerated
     */
    public Integer getnCode() {
        return nCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic.t_code_info.n_code
     *
     * @param nCode the value for basic.t_code_info.n_code
     *
     * @mbggenerated
     */
    public void setnCode(Integer nCode) {
        this.nCode = nCode;
    }
}