package com.tingyu.domain.book;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class TBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_id
     *
     * @mbggenerated
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_book_name
     *
     * @mbggenerated
     */
    private String cBookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_author_id
     *
     * @mbggenerated
     */
    private String cAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_author_name
     *
     * @mbggenerated
     */
    private String cAuthorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.n_book_type
     *
     * @mbggenerated
     */
    private Integer nBookType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_book_label
     *
     * @mbggenerated
     */
    private String cBookLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_book_intro
     *
     * @mbggenerated
     */
    private String cBookIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.n_word_count
     *
     * @mbggenerated
     */
    private Integer nWordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.c_cover_img
     *
     * @mbggenerated
     */
    private String cCoverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.n_publish_state
     *
     * @mbggenerated
     */
    private Integer nPublishState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.dt_publish_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy-MM-dd hh:mm:ss")
    private Date dtPublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.dt_create_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy-MM-dd hh:mm:ss")
    private Date dtCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.dt_last_modify_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy-MM-dd hh:mm:ss")
    private Date dtLastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_book.n_valid
     *
     * @mbggenerated
     */
    private Integer nValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @mbggenerated
     */
    public TBook(String cId, String cBookName, String cAuthorId, String cAuthorName, Integer nBookType, String cBookLabel, String cBookIntro, Integer nWordCount, String cCoverImg, Integer nPublishState, Date dtPublishTime, Date dtCreateTime, Date dtLastModifyTime, Integer nValid) {
        this.cId = cId;
        this.cBookName = cBookName;
        this.cAuthorId = cAuthorId;
        this.cAuthorName = cAuthorName;
        this.nBookType = nBookType;
        this.cBookLabel = cBookLabel;
        this.cBookIntro = cBookIntro;
        this.nWordCount = nWordCount;
        this.cCoverImg = cCoverImg;
        this.nPublishState = nPublishState;
        this.dtPublishTime = dtPublishTime;
        this.dtCreateTime = dtCreateTime;
        this.dtLastModifyTime = dtLastModifyTime;
        this.nValid = nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_book
     *
     * @mbggenerated
     */
    public TBook() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_id
     *
     * @return the value of book.t_book.c_id
     *
     * @mbggenerated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_id
     *
     * @param cId the value for book.t_book.c_id
     *
     * @mbggenerated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_book_name
     *
     * @return the value of book.t_book.c_book_name
     *
     * @mbggenerated
     */
    public String getcBookName() {
        return cBookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_book_name
     *
     * @param cBookName the value for book.t_book.c_book_name
     *
     * @mbggenerated
     */
    public void setcBookName(String cBookName) {
        this.cBookName = cBookName == null ? null : cBookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_author_id
     *
     * @return the value of book.t_book.c_author_id
     *
     * @mbggenerated
     */
    public String getcAuthorId() {
        return cAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_author_id
     *
     * @param cAuthorId the value for book.t_book.c_author_id
     *
     * @mbggenerated
     */
    public void setcAuthorId(String cAuthorId) {
        this.cAuthorId = cAuthorId == null ? null : cAuthorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_author_name
     *
     * @return the value of book.t_book.c_author_name
     *
     * @mbggenerated
     */
    public String getcAuthorName() {
        return cAuthorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_author_name
     *
     * @param cAuthorName the value for book.t_book.c_author_name
     *
     * @mbggenerated
     */
    public void setcAuthorName(String cAuthorName) {
        this.cAuthorName = cAuthorName == null ? null : cAuthorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.n_book_type
     *
     * @return the value of book.t_book.n_book_type
     *
     * @mbggenerated
     */
    public Integer getnBookType() {
        return nBookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.n_book_type
     *
     * @param nBookType the value for book.t_book.n_book_type
     *
     * @mbggenerated
     */
    public void setnBookType(Integer nBookType) {
        this.nBookType = nBookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_book_label
     *
     * @return the value of book.t_book.c_book_label
     *
     * @mbggenerated
     */
    public String getcBookLabel() {
        return cBookLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_book_label
     *
     * @param cBookLabel the value for book.t_book.c_book_label
     *
     * @mbggenerated
     */
    public void setcBookLabel(String cBookLabel) {
        this.cBookLabel = cBookLabel == null ? null : cBookLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_book_intro
     *
     * @return the value of book.t_book.c_book_intro
     *
     * @mbggenerated
     */
    public String getcBookIntro() {
        return cBookIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_book_intro
     *
     * @param cBookIntro the value for book.t_book.c_book_intro
     *
     * @mbggenerated
     */
    public void setcBookIntro(String cBookIntro) {
        this.cBookIntro = cBookIntro == null ? null : cBookIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.n_word_count
     *
     * @return the value of book.t_book.n_word_count
     *
     * @mbggenerated
     */
    public Integer getnWordCount() {
        return nWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.n_word_count
     *
     * @param nWordCount the value for book.t_book.n_word_count
     *
     * @mbggenerated
     */
    public void setnWordCount(Integer nWordCount) {
        this.nWordCount = nWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.c_cover_img
     *
     * @return the value of book.t_book.c_cover_img
     *
     * @mbggenerated
     */
    public String getcCoverImg() {
        return cCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.c_cover_img
     *
     * @param cCoverImg the value for book.t_book.c_cover_img
     *
     * @mbggenerated
     */
    public void setcCoverImg(String cCoverImg) {
        this.cCoverImg = cCoverImg == null ? null : cCoverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.n_publish_state
     *
     * @return the value of book.t_book.n_publish_state
     *
     * @mbggenerated
     */
    public Integer getnPublishState() {
        return nPublishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.n_publish_state
     *
     * @param nPublishState the value for book.t_book.n_publish_state
     *
     * @mbggenerated
     */
    public void setnPublishState(Integer nPublishState) {
        this.nPublishState = nPublishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.dt_publish_time
     *
     * @return the value of book.t_book.dt_publish_time
     *
     * @mbggenerated
     */
    public Date getDtPublishTime() {
        return dtPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.dt_publish_time
     *
     * @param dtPublishTime the value for book.t_book.dt_publish_time
     *
     * @mbggenerated
     */
    public void setDtPublishTime(Date dtPublishTime) {
        this.dtPublishTime = dtPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.dt_create_time
     *
     * @return the value of book.t_book.dt_create_time
     *
     * @mbggenerated
     */
    public Date getDtCreateTime() {
        return dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.dt_create_time
     *
     * @param dtCreateTime the value for book.t_book.dt_create_time
     *
     * @mbggenerated
     */
    public void setDtCreateTime(Date dtCreateTime) {
        this.dtCreateTime = dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.dt_last_modify_time
     *
     * @return the value of book.t_book.dt_last_modify_time
     *
     * @mbggenerated
     */
    public Date getDtLastModifyTime() {
        return dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.dt_last_modify_time
     *
     * @param dtLastModifyTime the value for book.t_book.dt_last_modify_time
     *
     * @mbggenerated
     */
    public void setDtLastModifyTime(Date dtLastModifyTime) {
        this.dtLastModifyTime = dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_book.n_valid
     *
     * @return the value of book.t_book.n_valid
     *
     * @mbggenerated
     */
    public Integer getnValid() {
        return nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_book.n_valid
     *
     * @param nValid the value for book.t_book.n_valid
     *
     * @mbggenerated
     */
    public void setnValid(Integer nValid) {
        this.nValid = nValid;
    }
}