package com.tingyu.domain.book;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class TChapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_id
     *
     * @mbggenerated
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_book_id
     *
     * @mbggenerated
     */
    private String cBookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_volume
     *
     * @mbggenerated
     */
    private String cVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_chapter_name
     *
     * @mbggenerated
     */
    private String cChapterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_spelling_code
     *
     * @mbggenerated
     */
    private String cSpellingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_chapter_intro
     *
     * @mbggenerated
     */
    private String cChapterIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.c_content
     *
     * @mbggenerated
     */
    private String cContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.n_word_count
     *
     * @mbggenerated
     */
    private Integer nWordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.n_publish_state
     *
     * @mbggenerated
     */
    private Integer nPublishState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.dt_publish_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy-MM-dd hh:mm:ss")
    private Date dtPublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.dt_create_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy-MM-dd hh:mm:ss")
    private Date dtCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.dt_last_modify_time
     *
     * @mbggenerated
     */
    private Date dtLastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.t_chapter.n_valid
     *
     * @mbggenerated
     */
    private Integer nValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @mbggenerated
     */
    public TChapter(String cId, String cBookId, String cVolume, String cChapterName, String cSpellingCode, String cChapterIntro, String cContent, Integer nWordCount, Integer nPublishState, Date dtPublishTime, Date dtCreateTime, Date dtLastModifyTime, Integer nValid) {
        this.cId = cId;
        this.cBookId = cBookId;
        this.cVolume = cVolume;
        this.cChapterName = cChapterName;
        this.cSpellingCode = cSpellingCode;
        this.cChapterIntro = cChapterIntro;
        this.cContent = cContent;
        this.nWordCount = nWordCount;
        this.nPublishState = nPublishState;
        this.dtPublishTime = dtPublishTime;
        this.dtCreateTime = dtCreateTime;
        this.dtLastModifyTime = dtLastModifyTime;
        this.nValid = nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book.t_chapter
     *
     * @mbggenerated
     */
    public TChapter() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_id
     *
     * @return the value of book.t_chapter.c_id
     *
     * @mbggenerated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_id
     *
     * @param cId the value for book.t_chapter.c_id
     *
     * @mbggenerated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_book_id
     *
     * @return the value of book.t_chapter.c_book_id
     *
     * @mbggenerated
     */
    public String getcBookId() {
        return cBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_book_id
     *
     * @param cBookId the value for book.t_chapter.c_book_id
     *
     * @mbggenerated
     */
    public void setcBookId(String cBookId) {
        this.cBookId = cBookId == null ? null : cBookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_volume
     *
     * @return the value of book.t_chapter.c_volume
     *
     * @mbggenerated
     */
    public String getcVolume() {
        return cVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_volume
     *
     * @param cVolume the value for book.t_chapter.c_volume
     *
     * @mbggenerated
     */
    public void setcVolume(String cVolume) {
        this.cVolume = cVolume == null ? null : cVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_chapter_name
     *
     * @return the value of book.t_chapter.c_chapter_name
     *
     * @mbggenerated
     */
    public String getcChapterName() {
        return cChapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_chapter_name
     *
     * @param cChapterName the value for book.t_chapter.c_chapter_name
     *
     * @mbggenerated
     */
    public void setcChapterName(String cChapterName) {
        this.cChapterName = cChapterName == null ? null : cChapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_spelling_code
     *
     * @return the value of book.t_chapter.c_spelling_code
     *
     * @mbggenerated
     */
    public String getcSpellingCode() {
        return cSpellingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_spelling_code
     *
     * @param cSpellingCode the value for book.t_chapter.c_spelling_code
     *
     * @mbggenerated
     */
    public void setcSpellingCode(String cSpellingCode) {
        this.cSpellingCode = cSpellingCode == null ? null : cSpellingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_chapter_intro
     *
     * @return the value of book.t_chapter.c_chapter_intro
     *
     * @mbggenerated
     */
    public String getcChapterIntro() {
        return cChapterIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_chapter_intro
     *
     * @param cChapterIntro the value for book.t_chapter.c_chapter_intro
     *
     * @mbggenerated
     */
    public void setcChapterIntro(String cChapterIntro) {
        this.cChapterIntro = cChapterIntro == null ? null : cChapterIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.c_content
     *
     * @return the value of book.t_chapter.c_content
     *
     * @mbggenerated
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.c_content
     *
     * @param cContent the value for book.t_chapter.c_content
     *
     * @mbggenerated
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.n_word_count
     *
     * @return the value of book.t_chapter.n_word_count
     *
     * @mbggenerated
     */
    public Integer getnWordCount() {
        return nWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.n_word_count
     *
     * @param nWordCount the value for book.t_chapter.n_word_count
     *
     * @mbggenerated
     */
    public void setnWordCount(Integer nWordCount) {
        this.nWordCount = nWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.n_publish_state
     *
     * @return the value of book.t_chapter.n_publish_state
     *
     * @mbggenerated
     */
    public Integer getnPublishState() {
        return nPublishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.n_publish_state
     *
     * @param nPublishState the value for book.t_chapter.n_publish_state
     *
     * @mbggenerated
     */
    public void setnPublishState(Integer nPublishState) {
        this.nPublishState = nPublishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.dt_publish_time
     *
     * @return the value of book.t_chapter.dt_publish_time
     *
     * @mbggenerated
     */
    public Date getDtPublishTime() {
        return dtPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.dt_publish_time
     *
     * @param dtPublishTime the value for book.t_chapter.dt_publish_time
     *
     * @mbggenerated
     */
    public void setDtPublishTime(Date dtPublishTime) {
        this.dtPublishTime = dtPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.dt_create_time
     *
     * @return the value of book.t_chapter.dt_create_time
     *
     * @mbggenerated
     */
    public Date getDtCreateTime() {
        return dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.dt_create_time
     *
     * @param dtCreateTime the value for book.t_chapter.dt_create_time
     *
     * @mbggenerated
     */
    public void setDtCreateTime(Date dtCreateTime) {
        this.dtCreateTime = dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.dt_last_modify_time
     *
     * @return the value of book.t_chapter.dt_last_modify_time
     *
     * @mbggenerated
     */
    public Date getDtLastModifyTime() {
        return dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.dt_last_modify_time
     *
     * @param dtLastModifyTime the value for book.t_chapter.dt_last_modify_time
     *
     * @mbggenerated
     */
    public void setDtLastModifyTime(Date dtLastModifyTime) {
        this.dtLastModifyTime = dtLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.t_chapter.n_valid
     *
     * @return the value of book.t_chapter.n_valid
     *
     * @mbggenerated
     */
    public Integer getnValid() {
        return nValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.t_chapter.n_valid
     *
     * @param nValid the value for book.t_chapter.n_valid
     *
     * @mbggenerated
     */
    public void setnValid(Integer nValid) {
        this.nValid = nValid;
    }
}